resources:
- ../.kube.yaml
patchesStrategicMerge:
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx
      namespace: nginx
    spec:
      template:
        metadata:
          labels:
            app: nginx
          name: nginx
          annotations:
            sidecar.istio.io/inject: "false"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/role: "nginx"
            vault.hashicorp.com/agent-inject-secret-dd: "nytm/nirmata/system-credentials/secret/nginx-cluster-002"
            vault.hashicorp.com/agent-inject-template-dd: |
              {{ with secret "nytm/nirmata/system-credentials/secret/nginx-cluster-002" -}}
                export DD_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
